In [1]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

Police set but without guard rails

In [2]:
result = pd.read_csv(r'D:\repos\dataengineering\yg821jf8611_il_statewide_2020_04_01.csv\il_statewide_2020_04_01.csv', index_col=0)

C:\Users\bjorn.bergdahl\AppData\Local\Temp\ipykernel_10396\659952621.py:1: DtypeWarning: Columns (3,4,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  result = pd.read_csv(r'D:\repos\dataengineering\yg821jf8611_il_statewide_2020_04_01.csv\il_statewide_2020_04_01.csv', index_col=0)

In [3]:
result.size
result.shape

result.sample(40)

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
5060787,2014-06-17,16:24:00,62002,11,NaN,hispanic,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,DODG,2003.0,4,2,0,2
12093762,2017-05-19,08:05:00,62814,4,NaN,white,male,13392.0,MOUNT VERNON POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,CHEVROLET,2014.0,1,1,6,1
1157042,2012-10-05,13:25:00,60531,9,NaN,hispanic,female,13451.0,OSWEGO POLICE,vehicular,...,False,False,NaN,Equipment,Oldsmobile,2003.0,4,2,0,2
7325265,2015-02-22,15:30:00,60518,17,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,PONT,2006.0,1,1,1,1
12459388,2017-07-17,13:45:00,60067.0,5,NaN,white,male,12992.0,SCHAUMBURG POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,MERCEDES-BENZ,2016.0,1,1,6,1
2049782,2012-12-03,22:10:00,0,11,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,NaN,1950.0,1,1,2,2
5831616,2014-12-03,19:07:00,60429,0002,NaN,white,female,13706.0,PEORIA HEIGHTS POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,NaN,2008.0,1,1,1,3
11865283,2017-04-01,01:14:00,60102.0,AREA TWO,NaN,white,male,13556.0,LAKE IN THE HILLS POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,SUBA,2017.0,1,1,1,1
8757291,2016-09-25,10:33:00,61565,2,NaN,white,female,13710.0,CHILLICOTHE POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,Toyota,2011.0,1,1,6,3
11478295,2017-04-09,13:19:00,62441,12,NaN,white,male,13823.0,ILLINOIS DEPARTMENT OF NATURAL RESOURCES POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,Ford,2010.0,1,1,4,2
4025732,2013-10-02,21:47:00,62526,JAK@AND,NaN,black,male,13692.0,SULLIVAN POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODGE,2006.0,2,1,1,1
4806322,2014-05-10,07:26:00,60634,0003,NaN,white,female,13179.0,ELMWOOD PARK POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,Acura,2009.0,1,1,1,1
3382436,2013-09-01,23:51:00,60046,63-1,NaN,white,male,13487.0,LINDENHURST POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,MITUBI,2002.0,1,1,1,3
1672630,2012-06-28,10:16:00,60802,15,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,SAAB,1998.0,1,1,1,1
9174588,2016-09-22,23:44:00,60123,1,NaN,hispanic,male,13048.0,HOFFMAN ESTATES POLICE,vehicular,...,False,False,NaN,License Plate/Registration,NISSAN,2012.0,4,3,0,3
3722165,2013-11-15,00:22:00,60462,A,NaN,white,female,13009.0,PALOS HEIGHTS POLICE,vehicular,...,False,False,NaN,Moving Violation: Follow too close,Hyundai,2009.0,1,1,5,3
8254911,2015-04-30,19:41:00,61104,65,NaN,black,male,13972.0,WINNEBAGO COUNTY SHERIFF,vehicular,...,False,False,NaN,Moving Violation: Other,chevy,2012.0,2,1,6,2
10690866,2017-03-22,21:21:00,60409.0,C4,NaN,white,male,13198.0,CALUMET CITY POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,Volvo,2007.0,1,1,4,3
1637439,2012-05-24,12:48:00,61101,16,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,DODG,1995.0,1,2,0,1
6412184,2015-10-20,09:25:00,61530,Beat 6,NaN,white,male,13581.0,BLOOMINGTON POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,ford,2013.0,1,1,1,3
9550177,2016-08-25,23:47:00,30088,I-24,NaN,black,male,13409.0,JOHNSON COUNTY SHERIFF,vehicular,...,False,False,NaN,Moving Violation: Speed,CHRYSLER,2005.0,2,1,1,1
4588372,2014-04-20,23:50:00,60634,2511,NaN,white,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,"TOYOTA MOTOR COMPANY, LTD.",2011.0,1,1,4,1
4198984,2013-01-05,22:43:00,60133,1,NaN,hispanic,female,13276.0,WOOD DALE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,FORD,2009.0,4,1,1,2
7302270,2015-08-30,15:04:00,61111,16,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,CHRY,2005.0,1,2,0,1
1628529,2012-05-14,09:08:00,38449,22,NaN,white,female,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,CHRY,2005.0,1,1,1,2
6338068,2015-05-28,12:21:00,60103,6A,NaN,white,female,13211.0,BARTLETT POLICE,vehicular,...,False,False,NaN,Equipment,HONDA,1997.0,1,2,0,2
4350785,2014-09-30,23:05:00,60104,0001,NaN,black,female,13208.0,BERKELEY POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,NaN,2003.0,2,1,1,1
11299586,2017-04-28,12:40:00,60901.0,E,NaN,white,female,13176.0,FLOSSMOOR POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,FORD,2016.0,1,1,1,3
4508562,2014-07-23,11:20:00,60475,G,NaN,white,male,13580.0,CHENOA POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,MITSUBISHI,2014.0,1,1,1,1
5472356,2014-02-19,22:22:00,60435,01000,NaN,hispanic,female,13943.0,LOCKPORT POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,HONDA,1998.0,4,1,1,1
4661470,2014-05-07,10:25:00,60429,3,NaN,black,male,13187.0,COUNTRY CLUB HILLS POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,Chevrolet,2011.0,2,1,2,1
5949924,2014-04-11,00:22:00,60073,04,NaN,white,male,13492.0,ROUND LAKE BEACH POLICE,vehicular,...,False,False,NaN,Equipment,CHEVROLET,2010.0,1,2,0,1
11521240,2017-02-18,22:30:00,60490,5,NaN,hispanic,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,HONDA,2012.0,4,2,0,1
11043916,2017-03-18,23:05:00,60525.0,SOUTH,NaN,white,female,13251.0,CLARENDON HILLS POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,AUDI,2013.0,1,1,1,1
11822190,2017-06-05,03:28:00,60136.0,RU04,NaN,hispanic,female,13425.0,KANE COUNTY SHERIFF,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,HONDA,2003.0,4,1,4,2
12382527,2017-06-01,13:15:00,61201,2,NaN,white,female,13757.0,ROCK ISLAND COUNTY SHERIFF,vehicular,...,False,False,NaN,Moving Violation: Other,FORD,2004.0,1,1,6,1
11856461,2017-06-25,16:32:00,60008.0,deer park,NaN,asian/pacific islander,female,13480.0,LAKE COUNTY SHERIFF,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,porsche,2016.0,5,1,4,3
3243179,2013-07-10,18:55:00,76247,5,NaN,hispanic,female,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,PONT,2009.0,4,2,0,1
5116797,2014-01-25,22:19:00,61821,10,NaN,black,female,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Equipment,NISS,2005.0,2,2,0,2
1410250,2012-09-04,13:11:00,60542,1,NaN,white,female,13276.0,WOOD DALE POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,CHEVROLET,2007.0,1,1,4,1

In [4]:
result.columns

Index(['date', 'time', 'location', 'beat', 'subject_age', 'subject_race',
       'subject_sex', 'department_id', 'department_name', 'type', 'violation',
       'citation_issued', 'warning_issued', 'outcome', 'contraband_found',
       'contraband_drugs', 'contraband_weapons', 'search_conducted',
       'search_person', 'search_vehicle', 'search_basis', 'reason_for_stop',
       'vehicle_make', 'vehicle_year', 'raw_DriverRace', 'raw_ReasonForStop',
       'raw_TypeOfMovingViolation', 'raw_ResultOfStop'],
      dtype='object')

In [5]:
result.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
1,2012-09-15,10:20:00,60641,1611,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,CHRYSLER,2004.0,4,1,4,1
2,2012-09-15,10:20:00,60189,1912,NaN,white,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,LEXUS,1999.0,1,1,2,1
3,2012-09-15,10:20:00,60638,815,NaN,hispanic,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,WHITE GMC (BEGIN. MODEL YEAR 1988),2010.0,4,1,6,1
4,2012-09-15,10:20:00,60638,925,NaN,white,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,CHEVROLET,2008.0,1,1,6,1
5,2012-09-15,10:21:00,NaN,2032,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,DODGE,2007.0,2,1,6,1

In [6]:
result.dtypes

date                          object
time                          object
location                      object
beat                          object
subject_age                  float64
subject_race                  object
subject_sex                   object
department_id                float64
department_name               object
type                          object
violation                     object
citation_issued                 bool
warning_issued                  bool
outcome                       object
contraband_found              object
contraband_drugs              object
contraband_weapons            object
search_conducted              object
search_person                 object
search_vehicle                object
search_basis                  object
reason_for_stop               object
vehicle_make                  object
vehicle_year                 float64
raw_DriverRace                 int64
raw_ReasonForStop              int64
raw_TypeOfMovingViolation      int64
raw_ResultOfStop               int64
dtype: object

In [7]:
result.count()

date                         12748173
time                         12737036
location                     12624518
beat                         12518024
subject_age                      8316
subject_race                 12747428
subject_sex                  12747842
department_id                12748173
department_name              12748173
type                         12748173
violation                    12748163
citation_issued              12748173
warning_issued               12748173
outcome                      12748172
contraband_found               574565
contraband_drugs               574519
contraband_weapons             574556
search_conducted             12731391
search_person                12731391
search_vehicle               12731256
search_basis                   189648
reason_for_stop              12748163
vehicle_make                 12408765
vehicle_year                 12735863
raw_DriverRace               12748173
raw_ReasonForStop            12748173
raw_TypeOfMovingViolation    12748173
raw_ResultOfStop             12748173
dtype: int64

In [8]:
result.isnull().sum()

date                                0
time                            11137
location                       123655
beat                           230149
subject_age                  12739857
subject_race                      745
subject_sex                       331
department_id                       0
department_name                     0
type                                0
violation                          10
citation_issued                     0
warning_issued                      0
outcome                             1
contraband_found             12173608
contraband_drugs             12173654
contraband_weapons           12173617
search_conducted                16782
search_person                   16782
search_vehicle                  16917
search_basis                 12558525
reason_for_stop                    10
vehicle_make                   339408
vehicle_year                    12310
raw_DriverRace                      0
raw_ReasonForStop                   0
raw_TypeOfMovingViolation           0
raw_ResultOfStop                    0
dtype: int64

OK so far it´s similar
But now we want only records with a contraband found.

In [9]:
contraband = result.loc[result['contraband_found'].isnull()==False]

In [10]:
contraband.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
36,2012-01-01,01:13:00,60653,724,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,License Plate/Registration,BUICK,2004.0,2,3,0,3
37,2012-01-01,01:14:00,60707,2531,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,License Plate/Registration,CADILLAC,2000.0,2,3,0,1
80,2012-01-01,07:33:00,60608,924,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,Moving Violation: Traffic Sign or Signal,CHEVROLET,1997.0,4,1,4,1
89,2012-01-01,09:05:00,60609,914,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,Moving Violation: Traffic Sign or Signal,CHEVROLET,1984.0,4,1,4,1
100,2012-01-01,10:30:00,60612,1532,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,Moving Violation: Other,CHEVROLET,2011.0,2,1,6,1

In [11]:
contraband.isnull().sum()

date                              0
time                            276
location                       2603
beat                          11671
subject_age                  574560
subject_race                      9
subject_sex                       7
department_id                     0
department_name                   0
type                              0
violation                         0
citation_issued                   0
warning_issued                    0
outcome                           0
contraband_found                  0
contraband_drugs                 46
contraband_weapons                9
search_conducted                  0
search_person                     0
search_vehicle                    0
search_basis                 386191
reason_for_stop                   0
vehicle_make                  28841
vehicle_year                    514
raw_DriverRace                    0
raw_ReasonForStop                 0
raw_TypeOfMovingViolation         0
raw_ResultOfStop                  0
dtype: int64

In [12]:
cleaned_contra = contraband.drop(['raw_DriverRace', 'raw_ReasonForStop', 'raw_TypeOfMovingViolation','raw_ResultOfStop'], axis = 'columns')

cleaned_contra.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,contraband_found,contraband_drugs,contraband_weapons,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year
raw_row_number,,,,,,,,,,,,,,,,,,,,,
36,2012-01-01,01:13:00,60653,724,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,License Plate/Registration,BUICK,2004.0
37,2012-01-01,01:14:00,60707,2531,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,False,True,True,True,True,NaN,License Plate/Registration,CADILLAC,2000.0
80,2012-01-01,07:33:00,60608,924,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,NaN,Moving Violation: Traffic Sign or Signal,CHEVROLET,1997.0
89,2012-01-01,09:05:00,60609,914,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,Moving Violation: Traffic Sign or Signal,CHEVROLET,1984.0
100,2012-01-01,10:30:00,60612,1532,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,Moving Violation: Other,CHEVROLET,2011.0

Well any prejudices?

In [13]:
result[result['subject_race'] == 'white'].search_conducted.value_counts(normalize=True)

search_conducted
False    0.963831
True     0.036169
Name: proportion, dtype: float64

In [14]:
print('blacks')

result[result['subject_race'] == 'black'].search_conducted.value_counts(normalize=True)

blacks

search_conducted
False    0.931292
True     0.068708
Name: proportion, dtype: float64

In [15]:
result.groupby('subject_race').search_conducted.value_counts(normalize=True)

subject_race            search_conducted
asian/pacific islander  False               0.984643
                        True                0.015357
black                   False               0.931292
                        True                0.068708
hispanic                False               0.937724
                        True                0.062276
other                   False               0.964709
                        True                0.035291
white                   False               0.963831
                        True                0.036169
Name: proportion, dtype: float64

In [21]:
output_contra = cleaned_contra.groupby('subject_race').contraband_found.value_counts(normalize=True)
output_contra

subject_race            contraband_found
asian/pacific islander  False               0.813277
                        True                0.186723
black                   False               0.779934
                        True                0.220066
hispanic                False               0.845401
                        True                0.154599
other                   False               0.844551
                        True                0.155449
white                   False               0.782014
                        True                0.217986
Name: proportion, dtype: float64

Any other metrics?
Age? Sex? Car age? (And how would you handle that one?)
Visualize?